name: Frontend Application

on:
  push:
    branches:
    - main


jobs:
  buils:
    runs-on: ubuntu-latest

    steps:
      
      - name: checkout code
        uses: actions/checkout@v4

      - name: Get base Image of Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install depedancy
        run: npm install

      - name: build application
        run: CI=false npm run build

      - name: build docker image
        run: docker build -t ecom-app .

       # Trivy Docker Image Scan
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ecom-app
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
   
      - name: test
        run: echo "test working"